### ISSUE TITLE
No GUI Notification

### ISSUE THREAD

**Issue by zorglub42** [andrehtissot/cordova-plugin-firebase-extended-notification#21] opened 2018-05-13 13:31 UTC
Hi andrehtissot 

I successfully succeed to build and deploy the example app on my phone (android 8.0).
I also succed to send a notif with the PHP example script, and if I add logging in the onNotification event I can see data coming when the app is running (foreground or background)

But, I don't have any badge nor notification in the android notification zone when the app is in background or closed. 

As well, when I click on the 'Show Notification' button nothing is coming

I also tried to add smth like:
`    FirebaseExtendedNotification.showNotification({dataValuesToGetWhenClickedOn: 111}, data.notificationOptions); 
`
in the onNotification event, but nothing is coming

Any idea of what's wrong?
Thx

**Comment by andrehtissot** [comment] 2018-05-14 18:04
Did you try running with the mock app? https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification-app-example

**Comment by zorglub42** [comment] 2018-05-14 18:37
Yeap.

But, just because something twice is better than once, I've just re-done it:

 `git clone https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification-app-example.git`
`cd cordova-plugin-firebase-extended-notification-app-example`
`cp $HOME/google-services.json app-example`
 Edited config.xml for id/package-name to suit my firebase json keys
`./install.sh`
Had to do this additionnel step to be able to build app
`cd app-example`
`cordova platforms remove android`
`cordova platfoms add android`
and run the app
`cordova run`

And.... still nothing.... notification pushed with php are received by the phone
(I can log it with adding `console.log(data)` in `FCMPlugin.onNotification`) 
but no badge, no notification in android notification zone.
Just in case:
cordova plugins list gives
cordova-plugin-fcm-with-dependecy-updated 2.2.4 "Cordova FCM Push Plugin"
cordova-plugin-firebase-extended-notification 1.8.1 "Firebase Extended Notification Cordova Plugin"
cordova-plugin-whitelist 1.3.3 "Whitelist"

cordova platforms gives
Installed platforms:
  android 7.0.0

And my phone is runnng Android 8.0

**Comment by andrehtissot** [comment] 2018-05-15 06:59
I understand.

Can you try to open the App Example and click on the "Show Notification" button?
This would "fake" the firebase push, just showing a nice notification. Also allowing you to change the values until you can se something happening. Useful in the case of only some options being incompatible in android 8.

Would you provide me the array sent as `notificationOptions` so I can check the format and try to reproduce this bug? You can change confidential info for dummy ones, of course.

I'll make more tests to this specific version later, until then it'd be great if you can send me more details.

**Comment by zorglub42** [comment] 2018-05-15 08:38
If I use the notify.php script as delivered here (https://github.com/andrehtissot/cordova-plugin-firebase-extended-notification-app-example/blob/master/server-side/notify.php) the result is the same: no notification.

On the mock app I tried to disable all fields except "Title" and then"Title+Text" but nothing is comming.

On my side I'll try to find a device running an older version of Android to check if the problem is linked to android 8 or not

**Comment by zorglub42** [comment] 2018-05-15 10:04
I found an Android 6 device and mock app is running properly. Notif are coming when I click the "Show notification" button.
As well, in the `FCMPlugin.onNotification` (index.js) if I add `FirebaseExtendedNotification.showNotification({dataValuesToGetWhenClickedOn: 111}, JSON.parse(data.notificationOptions))` notifications are coming when send via firebase with the php script.

**Comment by andrehtissot** [comment] 2018-05-16 07:29
Hi @zorglub42. I've found the issue.

From API level 26 up (Android 8.0+), to show a notification, it is required that the notification is linked to a "channel".

As right now, the target android version does not recognise the api methods to link it. Because of that, the fix wouldn't be just of code, it would also require some changes in the dependency versions.


I'll continue working on it and I'll post it as soon as I make any progress.

**Comment by andrehtissot** [comment] 2018-05-19 22:45
I'd like to thank you, @zorglub42, for this issue submission.

The bug is now fixed and the options `channelId`, `channelName` and `channelDescription` are now available to follow the new "way".

If these information are not provided, "default" options are used, allowing the notification to be presented.

In case of new bugs, don't hesitate to communicate me about it.

**Closed as completed by andrehtissot** 2018-05-19 22:45 UTC
